// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using csharpexam.Models;

namespace csharpexam.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20200622182544_csharpexam")]
    partial class csharpexam
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("csharpexam.Models.Association", b =>
                {
                    b.Property<int>("associationID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("gatheringID");

                    b.Property<int>("userID");

                    b.HasKey("associationID");

                    b.HasIndex("gatheringID");

                    b.HasIndex("userID");

                    b.ToTable("associations");
                });

            modelBuilder.Entity("csharpexam.Models.Gathering", b =>
                {
                    b.Property<int>("gatheringID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<DateTime>("date");

                    b.Property<string>("description")
                        .IsRequired();

                    b.Property<int>("duration");

                    b.Property<DateTime>("time");

                    b.Property<string>("title")
                        .IsRequired();

                    b.Property<int>("userID");

                    b.HasKey("gatheringID");

                    b.HasIndex("userID");

                    b.ToTable("gatherings");
                });

            modelBuilder.Entity("csharpexam.Models.User", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("email")
                        .IsRequired();

                    b.Property<string>("name")
                        .IsRequired();

                    b.Property<string>("password")
                        .IsRequired();

                    b.HasKey("userID");

                    b.ToTable("users");
                });

            modelBuilder.Entity("csharpexam.Models.Association", b =>
                {
                    b.HasOne("csharpexam.Models.Gathering", "gathering")
                        .WithMany("participants")
                        .HasForeignKey("gatheringID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("csharpexam.Models.User", "attendee")
                        .WithMany("attendinggatherings")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("csharpexam.Models.Gathering", b =>
                {
                    b.HasOne("csharpexam.Models.User", "coordinator")
                        .WithMany("plannedgatherings")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
